### PR TITLE
Complete app rework

### PR DESCRIPTION
**Pull request by cyb3rko**
Hi.
Thanks for this awesome template, I really appreciate your work and have already used it a lot in my projects.

The sample app was outdated and many methods and classes were deprecated or even not existent anymore, so I replaced them.
Furthermore I added NotNull/Nonnull annotations, fixed the non working back buttons and some minor fixes.

I just changed the important things, there are still thousands of warnings (redundant declarations, not perfect class structure, etc.).

Fixing all those warnings would take years, so first of all I'm gonna see what I can improve directly in the template so I can optimize the sample app much easier.

Currently I'm also learning Kotlin so maybe I can also help you with that.
As it's my first time using FreeMarker it could take some time.

Greetings!

### CODE REVIEW

**Comment by ckdevrel** [comment]
Thanks a lot for your contribution.. Merging the PR..

**Comment by cyb3rko** [comment]
Oh ok, thanks for your really quick answer.

Maybe you can test it by yourself if you can find any errors, because some parts had to be completely replaced because of using butterknife (which is deprecated for a long time already) etc...

**Comment by cyb3rko** [comment]
@TakeoffAndroid 
Did you find any errors?

**Comment by ckdevrel** [comment]
I have not checked it. Definitely I am gonna spend some time on this week to see how best to improve this..

**Comment by cyb3rko** [comment]
Ok, no hurry!
In the next days I will look into how to improve the current template because sometimes there are like 5 breaks without any code and of course the deprecated dependencies and methods have to get replaced.

**Pull request merged**
