### PR TITLE
Support Android Studio 3.6.2 and above, Migrate to androidX, Remove d…

### PR DESCRIPTION
**Pull request by MostafaAnter**
…eprecated ButterKnife

### CODE REVIEW

**Comment by MostafaAnter** [comment]
- Support android studio 3.6.2 or above solve problem #5 and #9 
- Migrate to androidX
- Remove ButterKnife

**Comment by cyb3rko** [comment]
It works fine now! Thanks a lot!
Appreciate it, I hope it gets implemented... (if something will ever happen here again; I hope so)

**Comment by MostafaAnter** [comment]
@cyb3rko thanks, you can directly download my [branch](https://github.com/MostafaAnter/RecyclerViewTemplate/tree/mostafa-anter) and use it until the merge is done.

**Comment by ckdevrel** [comment]
@MostafaAnter  Hey thanks for the contribution.. I just merged the PR..

**Comment by cyb3rko** [comment]
@MostafaAnter Yep, already did it yesterday.
Anyways, thanks!

**Pull request merged**
